name: Build thesis
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:1.16
    steps:
      - name: Install git lfs
        run: apk add --update --no-cache git-lfs

      - name: Install asciidoctor-lists
        run: gem install asciidoctor-lists

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Create build directory
        run: mkdir -p /work/build

      - name: Build PDF
        run: chmod +x ./scripts/asciidoc-to-pdf.sh && ./scripts/asciidoc-to-pdf.sh
        shell: bash

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: /work/build
